name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate snake SVG with black/bg + green snake
        uses: Platane/snk@v3
        with:
          github_user_name: sethogieva
          outputs: |
            dist/snake.svg
        env:
          SNAKE_COLOR: "#00FF66"
          SNAKE_BG: "#000000"

      - name: Push generated snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
